name: wf-dev-lint
on: 
  pull_request:
     branches:
       -develop
jobs: 
   lint-job:
     runs-on: ubuntu-latest
     steps:
       - name: checkout repo
         uses: actions/checkout@a4
       - name: Lint HTML and CSS
         run: 
           npx htmlhint "**/*.html"
           npx stylelint "**/*.css"
   build-job:
     needs: liont-job
     runs-on: ubuntu-latest
     steps:
       - name: checkout repo
         uses: actions/checkout@v4
       - name: Build With Parcel 
         run: |
          npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./" 
